# v2.6 TCN + Bi-Mamba + Dynamic GNN configuration
# Based on EvoBrain proven parameters for EEG

experiment:
  name: modal_tcn_gnn_v2.6
  description: "TCN + Bi-Mamba + Dynamic GNN with EvoBrain parameters"
  tags: ["tcn", "mamba", "gnn", "dynamic", "evobrain"]
  output_dir: results/modal
  seed: 42

model:
  architecture: tcn

  # Dynamic GNN configuration (EvoBrain proven)
  graph:
    enabled: true
    # Graph construction
    similarity: cosine  # EvoBrain default
    top_k: 3  # Proven best for EEG
    threshold: 1e-4  # Edge weight cutoff
    temperature: 0.1
    # GNN architecture
    n_layers: 2  # EvoBrain: 2-layer GNN
    dropout: 0.1
    use_residual: true
    alpha: 0.05  # SSGConv alpha for EEG
    # PyG specific (Phase 2)
    use_pyg: false  # Start with pure torch
    k_eigenvectors: 16  # Laplacian PE dimension

  tcn:
    num_layers: 8
    channels: [64, 128, 256, 512]
    kernel_size: 7
    dropout: 0.15
    causal: false
    stride_down: 16
    use_cuda_optimizations: true

  mamba:
    n_layers: 6
    d_model: 512
    d_state: 16
    conv_kernel: 4  # CUDA constraint
    dropout: 0.1

data:
  dataset_name: tusz
  train_manifest: data/manifests/train_manifest.csv
  val_manifest: data/manifests/val_manifest.csv
  cache_dir: .cache/eeg
  window_size_s: 60.0
  stride_s: 10.0
  num_workers: 8
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true

preprocessing:
  lowcut: 0.5
  highcut: 120.0
  notch_freq: 60.0
  notch_q: 30.0
  resample_freq: 256
  normalize: true
  clip_percentile: 99.9

training:
  epochs: 100
  batch_size: 64  # Reduce if OOM with GNN
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mixed_precision: true
  log_interval: 10
  val_interval: 1
  checkpoint_interval: 5

loss:
  name: focal
  focal_alpha: 0.5
  focal_gamma: 2.0
  pos_weight: 2.0
  logit_epsilon: 1e-6
  logit_clamp: 10.0
  reduction: mean

optimizer:
  name: adamw
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  name: onecyclelr
  max_lr: 0.001
  pct_start: 0.3
  anneal_strategy: cos
  div_factor: 25.0
  final_div_factor: 10000.0

postprocessing:
  hysteresis:
    tau_on: 0.86
    tau_off: 0.78
    min_onset_samples: 128
    min_offset_samples: 256
  morphology:
    opening_kernel: 11
    closing_kernel: 31
    use_gpu: true
  duration:
    min_duration_s: 3.0
    max_duration_s: 600.0
  events:
    tau_merge: 2.0
    confidence_method: mean
  stitching:
    method: overlap_add
    window_size: 15360
    stride: 2560

monitoring:
  use_wandb: true
  wandb:
    project: brain-go-brr-v2
    entity: jj-vcmcswaggins-novamindnyc
    name: tcn_gnn_v2.6
    tags: ["modal", "tcn", "gnn", "evobrain"]
  early_stopping:
    patience: 10
    monitor: val_loss
    mode: min
    delta: 0.001